[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.black]
line-length=120
skip-magic-trailing-comma = true

[tool.ruff]
line-length = 240 

[project]
name = "AstroToolkit"
version = "1.8"
authors = [
  { name="Ethan Moorfield", email="ethan.moorfield@hotmail.co.uk"},
]
description = "A package for the gathering, plotting and analysis of astronomical data."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
	"astropy",
	"astroquery",
	"pandas",
	"bokeh",
	"numpy",
	"pandas",
	"PyYAML",
	"matplotlib",
]

[project.urls]
Homepage = "https://github.com/WD-planets/AstroToolkit"
Issues = "https://github.com/WD-planets/AstroToolkit/issues"

[project.scripts]
# ATKgui = "bin.opengui_command:main"
# ATKquery = "bin.atkquery_command:main"
# ATKread = "bin.atkread_command:main"
# ATKsearch = "bin.atksearch_command:main"
# ATKconv = "bin.atkconv_command:main"
ATKconfig = "bin.atkconfig_command:main"
ATKalias = "bin.atkalias_command:main"
ATKepoch = "bin.atkepoch_command:main"
ATKoverlay = "bin.atkoverlay_command:main"
